version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword 
      MYSQL_DATABASE: formulario
      MYSQL_USER: toro
      MYSQL_PASSWORD: toro1234
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./formulario.html:/usr/share/nginx/html/formulario.html
      - ./style.css:/usr/share/nginx/html/style.css
      - ./conecion.php:/usr/share/nginx/html/conecion.php
      - ./Registrar.php:/usr/share/nginx/html/Registrar.php
      - ./tabla.php:/usr/share/nginx/html/tabla.php
      - ./validar.js:/usr/share/nginx/html/validar.js
    ports:
      - '81:80'

volumes:
  mysql-data:
